# Generated by Django 2.2.2 on 2019-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripIntent',
            fields=[
                ('intent_id', models.CharField(max_length=27, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(max_length=32)),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('delete_dttm', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
