# Generated by Django 2.2.2 on 2019-06-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='customer_id',
        ),
    ]
